In [2]:
import numpy as np

In [24]:
def Gauss_elim(coef, res):
    n = len(coef)
    for i in range(n):
        if len(coef[i]) != n:
            print("Invalid input- coefficient matrix not square")
            return None
    
    # Elimination- choose pivots, create triangular system
    
    coef = coef.astype(np.float64) # to solve an error
    E_inv = np.zeros((n,n)) # This will represent the product of inverse elementary matrices (chapter 1.5)
    for p in range(n):
        # M[p][p] will be pivot- want nonzero if possible
        if (coef[p][p] == 0):
            pivots = np.array([coef[i][p] for i in range(p,n)]) # list of possible pivots
            ind_max = abs(pivots).argmax() # choose largest pivot (in absolute value)
            #print(pivots[ind_max])
        
            if pivots[ind_max] == 0:
                print("Invalid input- singular matrix")
                return None
            
            coef[p], coef[ind_max + p] = coef[ind_max + p], coef[p] # swap lines to ensure nonzero pivot M[p][p]
            res[p], res[ind_max + p] = res[ind_max + p], res[p] # also swap RHS values
            E_inv[p], E_inv[ind_max + p] = E_inv[ind_max + p], E_inv[p] # and inverse matrix product
        
        # subtract multiples of line p from subsequent equations
        for i in range(p + 1, n):
            mult = coef[i][p] / coef[p][p]
            print(mult)
            
            coef[i][p:n] -= (mult * coef[p][p:n])
            res[i] -= (mult * res[p])
            E_inv[i][p] = mult # reasoning- equation (6), chapter 1.5
        
    # Backwards substitution- compute solution
    
    sol = np.empty(n)
    for i in range(n - 1, -1, -1):
        # subtract previously computed solutions from equation result
        for j in range(n - 1, i, -1):
            res[i] -= coef[i][j] * sol[j]
        
        # compute solution corresponding to coefficient M[i][i]
        sol[i] = (res[i] / coef[i][i])
        #print(res[i] / coef[i][i])
    
    # Recover initial coef matrix
    
    for i in range(n):
        E_inv[i][i] = 1 # complete E_inv by filling diagonal with 1
    coef = np.matmul(E_inv, coef) # recover initial coeficients
    
    print(coef)
    return sol
        

# Test for example matrix- system at the beginning of section 1.3
coef = np.array([[2, 1, 1], [4, -6, 0], [-2, 7, 2]])
res = np.array([5, -2, 9])

print(Gauss_elim(coef,res))
    

2.0
-1.0
-1.0
[[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]
[1. 1. 2.]
